language: python
install:
  - pip install tox
  - pip install coveralls
  - pip install -r test_requirements.txt
script:
  - tox
env:
  - TOXENV=django18
  - TOXENV=django19
after_success:
  coveralls
